baseurl = "https://example.com/"
theme = "cocoa-eh-eventcalendar"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Tobias Gerschner"
title = "Digital Youth Challenge Kapiti 2017"
disqusshortname = ""
pluralizelisttitles = false

# [permalinks]
# blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Digital Youth Challenge Kapiti 2017"
copyright = "Copyright © 2017 DLF Kapiti"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
latestpostcount = 5
github = "example"
email = "you@example.com"
linkedin = "john-example-aa80ue8è"
twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
