version: 2
jobs:
  build:
    docker:
     - image: tobig77/docker-hugo:latest
       environment:
         ENV: CI

    working_directory: ~/

    steps:
      - checkout
      - run: bash ci/publish.sh
